version: '3'

services:
  blog-php:
    container_name: ${COMPOSE_PROJECT_NAME}-php
    image: gouh/php:7.4-fpm-pdo-redis
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    env_file:
      - proyect.env
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}

  blog-install-project:
    container_name: ${COMPOSE_PROJECT_NAME}-install-project
    image: gouh/php:7.4-fpm-pdo-redis
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    working_dir: ${APP_CODE_PATH_CONTAINER}
    command: ["composer", "install"]
    links:
      - ${PHP_FPM_CONTAINER}

  blog-nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    image: nginx:alpine
    ports:
      - 0.0.0.0:${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/templates
    environment:
      - VIRTUAL_HOST=${NGINX_VHOST}
      - PHP_FPM_CONTAINER=${PHP_FPM_CONTAINER}
      - CODE_PATH=${APP_CODE_PATH_CONTAINER}
    links:
      - ${PHP_FPM_CONTAINER}
